[workspace]
members = [
    "halo2",
    "halo2_gadgets",
    "halo2_proofs",
]

[patch.crates-io]
funty = { version = "1.2", git = "https://github.com/ferrilab/funty", rev = "7ef0d890fbcd8b3def1635ac1a877fc298488446" }
